### ISSUE TITLE
Multiple keyword search

### ISSUE THREAD

**Issue by kyleseelman** [maxjo020418/BAScraper#3]
If I want to use the 'q=' param but with multiple possible keywords is that possible?

I can do "word1 word2 word3...", but then every post has to contain all of those words. I want it to be an and/or 

Thanks

**Comment by maxjo020418** [comment]
Sorry, the q param is a server side operation so I can't do anything about how it works.

The server owner said that the q string is an exact match and also all the words inside are stemmed/stopword removed.
so for example: "the cars are big" would search for exact match "car big". Performance hit for searches are too big so that was necessary. too bad I am not the maintainer nor owner of the PullPush server/service

only way of doing this is getting a bunch of data and then filtering them out (via spark of sql) or for small to moderate amounts use Google CSE(custom search engine) which has reddit indexed but a freemium model.
